name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Source/FreeBox.sln
    - name: Build
      run: dotnet build ./Source/FreeBox.sln --no-restore
    - name: Test
      run: dotnet test ./Source/FreeBox.sln --no-build --verbosity normal
